### ISSUE TITLE
Possibilitar escolher frete grátis por produto e por forma de envio

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-correios#11]
Atualmente, se colocar peso 0, o frete é grátis, porém para PAC e SEDEX e não para uma ou outra
Se pudesse escolher a forma de envio que será dado o frete grátis, assim como pode ser feito em frete grátis para X valor.
Solicitação https://community.e-com.plus/t/frete-gratis-atribuir-a-toda-categoria/951/15 da moça que ganhou os 3 meses grátis

**Comment by leomp12** [comment]
No caso de frete grátis por peso, vou "mockar" apenas na opção mais barata, em geral PAC, pode ser?

**Comment by matheusgnreis** [comment]
Pode, melhor

**Comment by matheusgnreis** [comment]
@leomp12 quando coloca o peso como 0, no PAC não está mostrando a forma de envio e SEDEX está mostrando um valor muito elevado. Não sei se é o caso, mas a versão aqui está como 1.1.12 e no painel está como 1.0.5, lembro de ver outro app nessa situação com a versão defasada.

**Comment by matheusgnreis** [comment]
O produto é https://www.entreminas.com/saofranciscoceramica-c544-c114-c188-c660
