### ISSUE TITLE
Adcionar tracking_url ao app 

### ISSUE THREAD

**Issue by vitorrgg** [ecomplus/app-correios#4]
Adicionar a url de rastreio dos correios para facilitar o trackeamento
 https://www2.correios.com.br/sistemas/rastreamento/default.cfm

**Comment by leomp12** [comment]
tl;dr: O lojista deve salvar o link no momento em que inserir o código, se no painel ele não tem como inserir o link um issue relativo a isto deve ser aberto em https://github.com/ecomplus/admin

Não dá pra tratar isto pelo app porque na Store API, no `orders`, o objeto do array `shipping_lines[].tracking_codes` tem uma propriedade requerida `code`, então só tem como setar o `shipping_lines[].tracking_codes[].link` se houver `shipping_lines[].tracking_codes[].code`.

> Em outras palavras: só dá pra salvar o URL de rastreamento junto ou depois de salvar o código de rastreamento, e o app dos Correios não faz isto porque não temos acesso a este dado.
