### ISSUE TITLE
Inserir na soma do tempo de entrega o valor de production_time.days

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-correios#7]
Já inserir no app dev e coloquei uma PR para ir pra produção. Coloquei tando nos produtos, quanto nas variações

**Comment by leomp12** [comment]
Na verdade isto não vai ser no app não, deve ser implementado no `storefront-app` pra aparecer no checkout e informações de pedido e talvez no `TheProduct` pra aparecer na página de produto.
