### ISSUE TITLE
Possível de cotação nos correios para localidades que a ecomenda é deixada na agencia

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-correios#9]
Uma das lojas reclamou na comunidade que faz entregas periódicas em um CEP (24431635) e é retornado com o seguinte corpo:
```
<Servicos>
<cServico>
<Codigo>04553</Codigo>
<Valor>96,74</Valor>
<PrazoEntrega>10</PrazoEntrega>
<ValorSemAdicionais>95,67</ValorSemAdicionais>
<ValorMaoPropria>0,00</ValorMaoPropria>
<ValorAvisoRecebimento>0,00</ValorAvisoRecebimento>
<ValorValorDeclarado>1,07</ValorValorDeclarado>
<EntregaDomiciliar>N</EntregaDomiciliar>
<EntregaSabado>S</EntregaSabado>
<obsFim>
O CEP de destino está temporariamente sem entrega domiciliar. A entrega será efetuada na agência indicada no Aviso de Chegada que será entregue no endereço do destinatário.
</obsFim>
<Erro>010</Erro>
<MsgErro>
O CEP de destino está temporariamente sem entrega domiciliar. A entrega será efetuada na agência indicada no Aviso de Chegada que será entregue no endereço do destinatário.
</MsgErro>
</cServico>
<cServico>
<Codigo>04596</Codigo>
<Valor>40,33</Valor>
<PrazoEntrega>24</PrazoEntrega>
<ValorSemAdicionais>39,26</ValorSemAdicionais>
<ValorMaoPropria>0,00</ValorMaoPropria>
<ValorAvisoRecebimento>0,00</ValorAvisoRecebimento>
<ValorValorDeclarado>1,07</ValorValorDeclarado>
<EntregaDomiciliar>N</EntregaDomiciliar>
<EntregaSabado>N</EntregaSabado>
<obsFim>
O CEP de destino está temporariamente sem entrega domiciliar. A entrega será efetuada na agência indicada no Aviso de Chegada que será entregue no endereço do destinatário.
</obsFim>
<Erro>010</Erro>
<MsgErro>
O CEP de destino está temporariamente sem entrega domiciliar. A entrega será efetuada na agência indicada no Aviso de Chegada que será entregue no endereço do destinatário.
</MsgErro>
</cServico>
</Servicos>
```
Aqui mostra https://github.com/ecomplus/app-correios/blob/master/routes/ecom/modules/calculate-shipping.js#L261 que se houver valor e prazo de entrega, teoricamente funcionaria. Segue uma chamada sem contrato para verificação

[Link correios](http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx?StrRetorno=xml&sCepOrigem=89026330&sCepDestino=24431635&nCdEmpresa=&sDsSenha=&nCdServico=04510&sCdMaoPropria=n&sCdAvisoRecebimento=n&nVlPeso=2.6&nVlValorDeclarado=127.9&nIndicaCalculo=3&nCdFormato=1&nVlDiametro=0&nVlComprimento=16&nVlAltura=2&nVlLargura=11)

**Comment by leomp12** [comment]
Não tá claro, você acha que não devemos retornar nada neste caso então? Não aperece a forma de envio?

**Comment by matheusgnreis** [comment]
Nesse caso, acho que deve mostrar. No momento não mostra, porque muitos desses casos o cliente já sabe que deve buscar a entrega nos correios, então deveria deixar ele receber

**Comment by leomp12** [comment]
Pronto @matheusgnreis :
![Screenshot_2020-09-02 Iphone 0 8Gb](https://user-images.githubusercontent.com/10326572/92039958-56561180-ed4c-11ea-82ab-25de2a0479b7.png)
